### ISSUE TITLE
Contact information / emails

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#1]
# UFAL: Contact information

lr.help.mail = dspace-help@clarin.***
lr.help.phone = +420-22191-4366
mail.from.address = dspace-noreply@clarin.***
mail.feedback.recipient = dspace-help@clarin.***
info.recipient = lindat-technical@clarin.***
mail.registration.notify = ${mail.admin}
# General site administration (Webmaster) e-mail

mail.admin = ${mail.feedback.recipient}

**Comment by tkrilavicius** [comment]
kažkur prie aukštesnio lygio adminų ar pan, reiktų
a.utka@hmf.vdu.**
+370 688 *****

**Comment by marsav** [comment]
Logiškiausia būtų kad Clarin turėtų savo e-mail adresus, ir jie būtų kur reikia forwardinami.
Pvz į a.utka@ galėtume nukreipti ${mail.admin} (konkrečiau kokį nors dspace-admin@clarin.vdu.lt)

Klausimas yra, ar galime kurti tokius emailus/po tokiu domenu, kaip kad nurodžiau aukščiau?

**Comment by tkrilavicius** [comment]
tada reiktų atitinkamų email adresų

lr.help.mail = dspace-help@clarin.***
lr.help.phone = +370 688 71853
mail.from.address = dspace-noreply@clarin.***
mail.feedback.recipient = dspace-help@clarin.***
info.recipient = repository-technical@clarin.***
mail.alert.recipient = ${mail.admin}
mail.registration.notify = ${mail.admin}

**Comment by Minotauras** [comment]
Čia Andrius turi nuspręsti, koks admino adresas (t.y. kas bus adminas).

**Comment by tkrilavicius** [comment]
andrius tik turės pasakyti, kam forwardus sudėti, o patys adresai tokie tegu ir būna

o sukūrimui reikia davidsono, bet jis gal dar neužsiregistravo

**Comment by uandrius** [comment]
Gal reiktų išsiimti dėžutę FC sistemoje, kurią matyčiau Aš, Tomas, Darius ir administratoriai, kuriuos paskirsime? Pvz.: clarin-lt@fc.vdu.lt Ten ir forwardintume visus messagus?

**Comment by tkrilavicius** [comment]
ar tikrai reikia fc?
bus visos tinkamos dėžutės clarin.vdu.lt, ir email iš mūsų kažkam forwardinsis? fc nebent aktualu, kad atsakinėjant kas nors neužmirštų likusiųjų pridėti

**Comment by uandrius** [comment]
OK, tik pagalvojau, kad taip būtų lengviau prijunti VDU dirbančius žmones, bet kita vertus juos nesunku prijungti ir iš clarin dėžutės. Tai galim ir nedaryti papildomo adreso.

**Comment by Minotauras** [comment]
Kazkokių dėžučių tikrai reikia, kur kreipti šiuos, help desk ir t.t. laiškus. Pritariu Tomui, kad FC reikėtų vengti, nes manau, kad tai merdintis reikalas, kurį gal pagaliau pavyks numarinti. bet šiai dienai kito korporacinio pašto neturime. Andriau, reikia Ritos paprašyti mums uždaros FC koferencijos ir pašto dėžučių. Kai kreipiasi projekto vadovas, daro be problemų. Užtenka parašyti per FC Ritai Misiūnaitei. Padarysi?

**Comment by marsav** [comment]
Tik pridėsiu savo trigrašį, kad visi tie aukščiau minėti Clarin-Dspace adresai gali būti (arba gali nukreipti į) mailing lists/grupes, kurių administravimui nebereiktų sysadmin pagalbos - tai reiškia, kad tose grupėse galėtų bet kas iš jūsų, bet kada prireikus pridėti arba išimti reikiamus el. adresus, naudojantis mailing list administravimo įrankiais.

Taip yra pasidarę ir čekai, ir daugelyje didesnių sprendimų panaši sistema naudojama, atskiriant sistemos administravimą nuo vidinės komunikacijos administravimo.

**Comment by Minotauras** [comment]
Ačiū, Martynai. Tada FC neišvengiamas. Arba Google grupsai. Google grupsas būtų administruojamas be jokių, net ir FC, adminų.

**Comment by adavidsonas** [comment]
Laiškus galima forwardinti vienam ar iškart keliems žmonėms. Reikia tik kad parašytumėte mail listo pavadinimą (\* eta clarin) ir kokiais adresais persiųsti. Tik nerašykite į šitą githubą, nes tie adresai greit pataps spam-iniai. Atsiųskit man paštu, geriau ne į FC, nes jo nenaudoju. Susitarti su FC adminais galiu, bet manau kiekvienas naudojame savo kažkokią pašto sistemą ir bandymas priversti dar kažkur jungtis papildomai (nesvarbu FC ar Gmail) nieko gero neduos, nes tai tikrai trukdo darbams. Susitvarkykite savo pašto sistemos aplankus, kad github ir clarin pranešimus gautumėte į juos ir neapsikraukime 100-u sistemų, mail-listų, prisijungimų, kurių pusė bus realiai nenaudojami.

**Comment by uandrius** [comment]
Atnaujinu diskusijas, kurios niekaip nepasibaigė
Sutinku su Andriumi D.  Tegul būna automatinė pašto sistema  (clarin taškas vdu taškas lt) domene kuriamos pašto dėžutės: dspace-help, dspace-noreply, dspace-technical. Tada pagalvosim kas kiekvienu atveju turės tas žinutes gauti. Telefonas gali būti mano. 
- Reiktų kad Andrius D. tą pašto sistemą sukonfigūruotų. 
- Ar čia dar yra kokių klausimų?

**Comment by marsav** [comment]
Perkonfigūravau dspace su nurodytais adresais/telefonais:
dspace-help, dspace-noreply, dspace-technical
+370 688 71853

kol kas visi jie - postfix alias'ai, nukreipiantys į dspace@
ateity galima bus ten nurodyti norimus mailing listus ar email adresus
