### ISSUE TITLE
Submission workflow/steps weeding

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#10]
Tomai, gal gali prisijungti su savo useriu ir praeiti tipinį submission procesą, ir surašyti man čia, jei reikia kokius žingsnius workflow'e išmesti ar pataisyti, ar jei susiduri su kokia problema.

**Comment by tkrilavicius** [comment]
O koks mano useris?

**Comment by marsav** [comment]
Userį sukūriau, prisijungimus atsiunčiau per skype.

**Comment by marsav** [comment]
Nuspręsta kol kas palikti default workflow. Uždarau kaip laikinai baigtą.
