### ISSUE TITLE
XMLUI i18n - sync resources

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#12]
Reikia susinchronizuoti messages resursą (https://github.com/marsav/lindat-dspace/blob/clarin-lt/dspace-xmlui/src/main/webapp/i18n/messages_lt.xml) su prikabintu failu (iš kito projekto), t.y. perkelti atitinkamus lietuviškus vertimus.

Message identifikatoriai gali skirtis, reikia užtikrinti, kad perkeliant vertimus, išliktų mūsiškio failo message identifikatoriai.
- [xmlui_messages_lt.xml.zip](https://github.com/marsav/lindat-dspace/files/77328/xmlui_messages_lt.xml.zip)

i18n placeholder: #11

**Comment by IevaBumbuliene** [comment]
Noriu pasitikslinti. Eilutes su vienodais "key" tiesiog pakeisti į Github'e esantį failą, o likusius angliškus pačiai išversti?

**Comment by marsav** [comment]
Taip, teisingai. Reikia kad liktų eilutės su visais originaliais "key", buvusiais originaliame faile, tik būtų išverstos. Tas prikabintas failas tiesiog turėtų palengvinti darbą, kad nereiktų visko rankomis versti. Be to, jis demonstruoja vertimo stilių.

**Comment by marsav** [comment]
@IevaBumbuliene kad būtų paprasčiau patikrinti rezultatą, siūlau padalinti šį darbą į dvi dalis:
1) pirmiausia sulieti jau esamus vertimus, tada commit'inti atnaujintą failą
2) aš patikrinsiu, ir tada galima bus antru žingsniu išversti likusias eilutes, tada vėl commit'inti failą

**Comment by ievbu** [comment]
Įkėliau failą. Laukiu komentarų ar viskas gerai ir po to darysiu toliau.

**Comment by marsav** [comment]
@IevaBumbuliene sujungta gerai, netikslumus ir klaidas galėsime taisyti vėliau, kol kas gerai būtų išversti likusius angliškus tekstus. Vertimų turinio klausimams ir patikslinimams sukursiu atskirą issue. Commit komentaruose pridėk susijusio issue numerį (šio failo atveju tai #13).

**Comment by marsav** [comment]
Deployed
