### ISSUE TITLE
Epic: Handle Server

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#14]
Iš čekų laiško:

> 2) deciding whether to use local or EPIC handle prefix  - I suggest a local one which means getting it from http://handle.net/service_agreement.html;
> 3) initiating the process of becoming a member of the Lithuanian identity federation (http://fedi.litnet.lt/) - this usually takes the most of the time.
> You need an actual service to complete 3) and in this case it is the repository itself.

**Comment by marsav** [comment]
@tkrilavicius gal gali pakomentuoti koks šiuo metu statusas su FEDI, tas aukščiau minėtas procesas inicijuotas?

**Comment by tkrilavicius** [comment]
VDU keitėsi IT vadai, tai dar net nerado, su kuo aiškintis. Žiūrėsim, kas bus

**Comment by marsav** [comment]
@uandrius commented:

> Čia geras klausimas ką darome su tuo handle serveriu? Kaip suprantu, tai galima padaryti per "handle.net"? Ar kokį sprendimą mes pasirenkame?
> get prefix
> ○ http://handle.net/service_agreement.html
> ○ approx. costs: $50 (first time) + $50 (annually)

**Comment by marsav** [comment]
From #25, uandrius wrote:

> prefix'ą, beje jau jį gavau, tik kaip suprantu kol nebus apmokėta jis neveiks. Apmokėjimas gali užtrukti porą savaičių.

**Comment by tkrilavicius** [comment]
jau turėtų veikti
