### ISSUE TITLE
Mail: Relay access denied

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#17]
```
Jan  6 16:57:59 clarin postfix/smtpd[64534]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 554 
5.7.1 <***>: Relay access denied; from=<***> to=<***> proto=ESMTP helo=<clarin>
```

**Comment by adavidsonas** [comment]
Prideti reverse DNS įrašai. Būtų gerai jei galėčiau pats tą klaidą atgaminti (kaip siunčiama? kokios komandos naudojamos?), nes kiek pats siunčiu ar iš serverio, ar į serverį laiškus, juos tvarkingai gaunu. Gal problema su pačio serviso konfigūracija ar netaisyklingu siuntimu?

**Comment by marsav** [comment]
Kol kas tai nepadėjo. Problemą galima atkartoti taip:

```
(export $DSPACE_INSTALLATION_DIRECTORY=/opt/lindat-dspace/installation)
sudo $DSPACE_INSTALLATION_DIRECTORY/bin/dspace test-email
```

Dspace mail serviso settings nusistato čia:

```
 $DSPACE_INSTALLATION_DIRECTORY/config/dspace.cfg
```

Aukščiau minėta test-email komanda siunčia emailą adresu nurodytu konfige mail.admin. Jei ten nurodyti vidinį adresą, praeina be problemų.
Papidlomi DSpace settingai:

```
mail.server
mail.server.username
mail.server.password
mail.server.port
mail.from.address
```

JavaMail settings, pastarieji čia greičiausiai ir esminiai, nusirodo (šiuo metu užkomentavau visus):

```
# Pass extra settings to the Java mail library. Comma-separated, equals sign between
# the key and the value. For example:
#mail.extraproperties =  mail.smtp.starttls.enable=true, \
#                       mail.smtp.auth=true
#                       mail.smtp.socketFactory.port=587
#                       mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory, \
#                       mail.smtp.socketFactory.fallback=false
```

**Comment by marsav** [comment]
O čia JavaMail property list: https://javamail.java.net/nonav/docs/api/com/sun/mail/smtp/package-summary.html

**Comment by marsav** [comment]
Fixed
