### ISSUE TITLE
Branding - About page

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#24]
Reiktų savos versijos About/Apie, pažiūrėkite, gal kažkas tinka iš čekų (kurių versija šiuo metu pas mus ir guli):
https://clarin.vdu.lt/xmlui/page/about

Taip pat reiktų lietuviškos versijos, jei jau dviem kalbom viskas.

Susiję su Branding: #4

**Comment by uandrius** [comment]
Supratau, čia reiks padirbėti. Kol kas, kad nebūtų tuščias gali būti "Mission statement", "About Repository" su kitomis dalimis dar reikia padirbti

**Comment by marsav** [comment]
Palikau tik "Mission statement", "About Repository".
Peradresuoju užduotį jums, @uandrius - kai bus pakeitimų, perduokite juos ir šią užduotį atgal man.

**Comment by marsav** [comment]
A.U:

> Reiktų išjungti/išimti visus mygtukus (taip pat ir footeryje) kurie veda į CLARIN-LT.lt puslapius išskyrus, per "Logotipą", Meniu juostoje/footeryje galėtų būti Saugyklos "News", ir "Legal information".Tegul Saugykla būna atskiras puslapis
> 
> "About" reiktų pakeisti į legal information, juk yra krūva dokumentų "Privacy Policy", "Terms of Service", "Distribution licence agreement",  "End user licences".
> Legal information reiktų turėti viršuje meniu juostoje šalia "Repository", o ten atskiros nuorods į PrivacyPol, Tos, DLA, EULA (Tada meniu juostoje būtu, News, Repository, Legal Information).

**Comment by marsav** [comment]
Pakeitimai atlikti, @uandrius perduodu patikrinimui
