### ISSUE TITLE
Branding - Footer / Repository section

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#25]
Susiję: #4, #24 
Šiuo metu footer Repository skyriuje (kurį kaip supratau, buvo siūlyta palikti), yra žemiau pateiktos nuorodos. PGal galite peržiūrėti ir patvirtinti, kad tuose puslapiuose nereikia nieko pakeisti, kad atitiktų lietuviškas realijas.

Main page -> bus nukreipta į pagrindinį Clarin-LT Repo
Submission Lifecycle -> http://clarin.vdu.lt:8080/xmlui/page/item-lifecycle?locale-attribute=en
FAQ -> http://clarin.vdu.lt:8080/xmlui/page/faq?locale-attribute=en
About and Policies -> http://clarin.vdu.lt:8080/xmlui/page/about?locale-attribute=en

Contact -> šiuo metu rodo į https://lindat.mff.cuni.cz/en/about-lindat-clarin - ši dalis aptariama #23

**Comment by uandrius** [comment]
Sumbission Lifecycle - gali likti toks pats tik LINDAT -> CLARIN LT ir prefix'as pasikeis pagal mūsų prefix'ą, beje jau jį gavau, tik kaip suprantu kol nebus apmokėta jis neveiks. Apmokėjimas gali užtrukti porą savaičių.
FAQ - tas pats.
About ir policies - jau rašiau, #24.
Contact gali rodyti į  http://clarin-lt.lt/?page_id=91, arba pateikti panašią "Partners" lentelę  su nuorodomis į VDU, VU ir KTU.

**Comment by marsav** [comment]
Sumbission Lifecycle - pakeista LINDAT -> CLARIN LT
About ir policies - laikinai sutrumpinta kaip nurodyta #24, bei pakeista LINDAT -> CLARIN LT
Contact - nukreiptas į clarin-lt anglišką kontaktų psl. http://clarin-lt.lt/?page_id=93

Pakeitimai:

``` /opt/lindat-dspace/installation/webapps/xmlui/themes/UFALHome/lib/xsl/page-structure.xsl
/opt/lindat-dspace/installation/webapps/xmlui/themes/UFAL/lib/html/about.html
/opt/lindat-dspace/installation/webapps/xmlui/themes/UFAL/lib/html/item-lifecycle.html
/opt/lindat-dspace/installation/webapps/xmlui/themes/UFAL/lib/lindat/footer.htm
/opt/lindat-dspace/installation/webapps/xmlui/themes/UFAL/lib/lindat/header.htm
```

**Comment by marsav** [comment]
Uždarau kaip išspręstą, Submission Lifecycle handle pakeitimą iškėliau į #26
