### ISSUE TITLE
Dspace Handle Server setup (tech)

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#28]
Parent: #14 

Instructions: 
- https://github.com/ufal/lindat-dspace/wiki/Handle-Server
- https://github.com/ufal/lindat-dspace/wiki/Installation----Prerequisites#handles
- https://wiki.duraspace.org/display/DSDOC5x/Installing+DSpace#InstallingDSpace-TheHandleServer
- http://wiki.lib.sun.ac.za/index.php/SUNScholar/Handle_Server

Notes:
1. The Handle protocol is based on TCP, so it will need to be installed on a server that can send and receive TCP on port 2641. HTTP post 8000 has also be opened for access.
2. Each handle site has a version/serial number assigned to it. This is so that a client can tell if a particular site's configuration has changed since the last time it accessed a server in the site.  Every time you modify a site (by changing an IP address, port, or adding a server, etc), you should increment the version/serial number for that site.
3. Handle prefix 20.500.11821 has been allotted to you
4. The Handle System can communicate via UDP and/or TCP sockets.
Since UDP messages are blocked by many network firewalls, you may want to disable UDP services if you are behind such a firewall.

**Comment by marsav** [comment]
http://www.handle.net/prefix_request.html

sitebundl.zip File Upload

For new registrants, the final step in the HANDLE.NET® Software download and registration process is to upload the sitebndl.zip file generated by running the hdl-setup script (following the instructions in the README.txt file included with the software distribution) to the HNR Administrator, who will then create and activate your allotted prefix.

Existing users who move their handle server to new hardware, change a server's IP Address or otherwise change their server's configuration must re-run the hdl-setup script to generate an updated sitebundl.zip file. Send questions about your server update or requests for further information to the HNR Administrator at xxx at cnri.reston.va.us, and be sure to identify the prefix to be updated in your email message.

**Comment by marsav** [comment]
sitebundl.zip response:

[...]
You will receive a response from the HNR Administrator within the next 48 hours. Questions should be sent to hdladmin at cnri.reston.va.us

**Comment by marsav** [comment]
Installation steps 1-3 complete. Current status:
"An [handle.net] administrator will then create the naming authority/prefix on the root service (known as the Global Handle Registry), and notify you when this has been completed. You will not be able to continue the handle server installation until you receive further information concerning your naming authority."

**Comment by marsav** [comment]
@adavidsonas reikia atidaryti:  TCP on port 2641, HTTP on port 8000

handle faq: https://www.handle.net/faq.html#T28

**Comment by adavidsonas** [comment]
Portai atidaryti.

**Comment by marsav** [comment]
> Your prefix has been created.  Let us know if you have any issues setting up your handle server or getting your handles to resolve.

**Comment by marsav** [comment]
Laukiama patikslinimo dėl 'Init scripts' dalies
@tkrilavicius žr. email paklausimą

**Comment by marsav** [comment]
@adavidsonas Dar dėl portų, kitoj vietoj radau tokį reikalavimą:
http://wiki.lib.sun.ac.za/index.php/SUNScholar/Handle_Server#Step_8_-_Firewall_Ports

> Ports 8000 and 2641 must be opened to listen via UDP and TCP to the handle server: http://hdl.handle.net

Ar gali patvirtint kad tie portai atviri UDP ir TCP?

**Comment by marsav** [comment]
Handle serveris šiuo metu paleistas iš root. Galima patikrinti:

```
http://clarin.vdu.lt:8000/
```

suvedant: 20.500.11821/3 ar kitą egzistuojantį handle.

**Comment by marsav** [comment]
Išriša teisingai: http://hdl.handle.net/20.500.11821/3

**Comment by marsav** [comment]
Pridėta į /etc/rc.local, restartui.
Handle server setup baigtas.

**Comment by adavidsonas** [comment]
Dėl portų: visi portai localhost-ui atviri. Taigi servisai tarpusavyje gali bendrauti be apribojimų. 
 8000 ir 2641 atviri tik TCP. Ar pridėti ir UDP?

**Comment by adavidsonas** [comment]
Startup skriptus dėti į /etc/rc.local yra bloga mintis. Taip darydavom prieš 10 metų kai nebuvo normalios init sistemos ir turėdavom eilę visokių problemų. Siūlyčiau rašyti normalų init skriptą ir jei įmanoma pleidinėti ne root teisėmis.

**Comment by marsav** [comment]
Čia padariau kaip rekomendavo dokumentacijoje, bet supratau mintį,
pažiūrėsiu ką galima padaryt.

**Comment by marsav** [comment]
Dėl portų: čia bus kreipiamasi iš išorės (handle.com). Bet panašu kad TCP
užteko, nors dokumentacijoje mini abu protokolus. Tai paliekam kaip yra,
nes šiuo metu mano testai veikia - jei kils problemų, tvarkysim tada.

**Comment by adavidsonas** [comment]
Jei el. paštu atsiųsite komandas su kuriomis turėtų būti paleidžiamas, stabdomas, perkraunamas servisas bei nurodysite kokio vartotojo teisėmis, skriptą galiu parašyti ir įkelti (nepažadu šiandien).
