### ISSUE TITLE
Shibboleth installation

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#29]
Parent: #7 

Reikia instaliuoti Shibboleth. 
Informacija/nuorodos:
1. https://github.com/ufal/lindat-dspace/wiki/Shibboleth_install
2. https://github.com/ufal/lindat-dspace/wiki/Building-Shibboleth-with-FastCGI-support
3. https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPLinuxInstall
4. https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPLinuxSRPMBuild

Esminiai dalykai:

"Shibboleth can be built on most versions of 32- and 64-bit Linux, but is officially supported only on the following distributions at this time:
Red Hat Enterprise and CentOS 5, 6, 7
SUSE Linux Enterprise Server 10, 11, 11-SP1, 11-SP2, 11-SP3, 11SP4, 12, 12SP1
OpenSUSE Linux 13.1, 13.2" [3]

"If your distribution supports the RPM package manager, it is strongly suggested that you install using RPMs built for your specific distribution, or by rebuilding the SRPM source packages provided. If this is not possible, you can build from source." [3]

Neteisingų buildų instaliavimas gali būti sunkiai pataisomas, todėl svarbu šituos žingsnius padaryti tinkamai. Žr. instrukcijas buildui iš SRPM [4]

Pirmas žingsnis - pačių yum ir rpmbuild instaliavimas.

**Comment by adavidsonas** [comment]
yum ir rpmbuild debian nepalaiko ir jų diegimas yra pavojingas.
Kuo būtų blogai jei būtų pasinaudota debian backport-ais:
https://uit.stanford.edu/service/shibboleth/sp/debian

Pilnas diegimas:
https://uit.stanford.edu/service/shibboleth/sp
Service provider-iai ne tie, bet greičiausiai galima pasikoreguoti pagal tai ko reikia.

Dar vienas pliusas, kad tai standartinis būdas ir skirtingai nei buildinant from sources, galima bus standartiniu būdu perinstaliuoti/išmesti ir pan.

**Comment by marsav** [comment]
Andrius D.:

> Jessie backport-ai jau yra pridėti.
> libapache2-mod-shib2 įdiegtas
> shib2 aktyvavau.
> Belieka prisitaikyti savo atvejui likusius žingsnius.

**Comment by marsav** [comment]
```
/usr/sbin/shibd -v
shibboleth 2.5.3
```

Instaliacija baigta, sekantis žingsnis - konfigūracija (žr. #30)
