### ISSUE TITLE
Shibboleth konfigūravimas ir instaliavimas

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#30]
Parent: #7 
Atliekamas baigus Shibboleth instaliavimą (#29).

FEDI
- Techniniai Litnet Fedi reikalavimai: http://www.fedi.litnet.lt/lt/11-technines-instrukcijos/30-techniniai-litnet-fedi-reikalavimai

SCCTC (from a Feb 24 mail)
- information about setting up and testing an SP (The testing is mentioned in section 3): 
  https://www.clarin.eu/content/creating-and-testing-shibboleth-sp
- More information is on trac.clarin.eu (requires login): https://trac.clarin.eu/wiki/ServiceProviderFederationLoginTest

**Comment by marsav** [comment]
Sėkmingas preliminarus Shibboleth instaliacijos testavimas testshib pagalba.

**Comment by marsav** [comment]
Metadata konfigūravimas Clarin ERIC SPF pagal
https://cdn.rawgit.com/clarin-eric/SPF-tutorial/master/Shib_SP_tutorial.html
Atlikti žingsniai:
- 4.1.2
- 4.1.3
- 4.1.4
- 4.2
- 4.3 - 1..8

Toliau laukiama vartotojo patvirtinimo, metaduomenų pateikimui į Clarin ERIC SPF SVN repozitorijai.

**Comment by marsav** [comment]
Atlikti tolesni žingsniai:
4.3. - ..9

Metadata iš SVN matyt buvo priimta, nes pagaliau Dspace Login kreipinys priimamas Clarin.eu, tačiau ten sėkminga autentifikacija "nepraeina" atgal. Ieškau problemos ir sprendimo.

**Comment by marsav** [comment]
> 25 Aug
> You have recently committed SAML metadata about an SP to the CLARIN Service Provider Federation SVN at https://svn.clarin.eu/aai/clarin-sp-metadata.xml . Please consider the following remarks concerning SP SAML metadata management.
> 
> Please ascertain that you comply with https://www.clarin.eu/content/guidelines-saml-metadata-about-your-sp , e.g. by checking and resolving issues with the SAML metadata quality for your SP before and after your commit as listed in the spreadsheet at https://goo.gl/Nl0DCH . Finally, with e.g. Shibboleth SP, please do update the SAML metadata template of your SP to make the SAML metadata generation handler produce the same SAML metadata as you deposit here (see e.g. https://goo.gl/uysudA ). If you've added a new SP, or wish that the registration/modification of the SAML metadata about your SP with identity federations is coordinated extra carefully (say, you perform a key rollover), then please head over to https://trac.clarin.eu/newticket and create a ticket for the 'AAI' Trac component, describing the task. Thanks!
> 
> The CLARIN Service Provider Federation

**Comment by marsav** [comment]
`clarin-sp-metadata.xml` atnaujinta (svn commited):

```
<md:AttributeConsumingService index="1">
...
    <md:RequestedAttribute 
        FriendlyName="eduPersonPrincipalName" 
        Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6" 
        NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" 
        isRequired="true"/>
     <md:RequestedAttribute 
        isRequired="false" 
        FriendlyName="mail" 
        Name="urn:mace:dir:attribute-def:mail"
        NameFormat="urn:mace:shibboleth:1.0:attributeNamespace:uri"/>
    <md:RequestedAttribute
        isRequired="false"
        FriendlyName="mail"
        Name="urn:oid:0.9.2342.19200300.100.1.3"
        NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"/>
</md:AttributeConsumingService>
```

**Comment by marsav** [comment]
SPF konfigūracija sutvarkyta, autentikacija per Clarin.eu pavyko (žr. prikabintą screenshot).

![screen shot 2016-09-02 at 18 37 56](https://cloud.githubusercontent.com/assets/1196273/18209461/8690a53a-713c-11e6-80e2-cc90553b6ac0.png)

**Comment by marsav** [comment]
@tkrilavicius @uandrius Patikrinkite ir uždarykite GitHub issue jei veikia.

**Comment by tkrilavicius** [comment]
man meta klaidą

ERROR

An error occurred while processing your request. Please contact your helpdesk or user ID office for assistance.

This service requires cookies. Please ensure that they are enabled and try your going back to your desired resource and trying to login again.

Use of your browser's back button may cause specific errors that can be resolved by going back to your desired resource and trying to login again.

If you think you were sent here in error, please contact technical support

Error Message: SAML 2 SSO profile is not configured for relying party https://sp.clarin.vdu.lt

**Comment by marsav** [comment]
@tkrilavicius Ar bandei, kaip nurodyta, įjungt cookies? Arba white-listint clarin.vdu.lt jei naudoji kokį cookies-blocker plugin, kaip pvz. Disconnect.

**Comment by marsav** [comment]
Atnaujinti kontaktiniai duomenys

```
martynas$ svn commit ./clarin-sp-metadata.xml -m "Providing CLARIN-LT's contact details"
Sending        clarin-sp-metadata.xml
Transmitting file data .
Committed revision 7092.
```
