### ISSUE TITLE
Item submissions: No collections found

### ISSUE THREAD

**Issue by marsav** [marsav/lindat-dspace#33]
(Prisijungus per clarin.eu)

> prisijungiu prie per CLARIN acount, tačiau kažkodėl negaliu inicijuoti Deposit funkcijos.
> - paspaudžiu "Submission"
> 
> ![unnamed](https://cloud.githubusercontent.com/assets/1196273/18577605/692a934a-7bf3-11e6-9f42-cebc63e95fe0.png)
> - tada "start another submission" ir tada

**Comment by uandrius** [comment]
Martynai, kas su šituo bug'u?

**Comment by marsav** [comment]
Kaip buvo kalbėta email, tai teisių klausimas. Administratoriai turi priskirti atitinkamoms communities/kolekcijoms Anonymous-WRITE teises per administravimo paskyrą, kaip tai dabar padariau Test community/collection.
